version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5001
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
